name: Binaries (stable)

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Force building of this tag"
        type: string
        required: false
      test:
        description: "Deploy to test location"
        type: boolean
        default: true

  schedule:
    - cron: "30 2 * * *" # Triggers the build daily at night

jobs:
  check_build:
    name: Check if we need to run the pipeline or not
    runs-on: ubuntu-latest
    outputs:
      action: ${{ steps.verify.outputs.action }}
      release: ${{ steps.verify.outputs.release }}
      commit: ${{ steps.verify.outputs.commit }}
    steps:
      - name: Checkout binary-distribution
        uses: actions/checkout@v6
        with:
          path: binary-distribution
      - id: verify
        name: Determine whether there are releases to build
        run: |
          git ls-remote https://github.com/ocaml/dune.git | grep refs/tags/ | grep -v {} | sed 's#refs/tags/##' > remote
          cut -f 2 < remote > tags
          DUNE_RELEASES=$(grep -v alpha < tags | grep -v beta | sort -V | tail -n 10)
          jq -r "[.[]?|.tag]|sort|.[]" < binary-distribution/metadata-stable.json > built
          BUILT=$(xargs < built)
          echo "Built so far: $BUILT"
          echo "Dune releases are $DUNE_RELEASES"
          if [ -z "${{ inputs.release }}" ]; then
            # no release specified, determine what to build
            for release in $DUNE_RELEASES; do
              if ! grep -x "$release" built > /dev/null; then
                echo "action=BUILD" >> "$GITHUB_OUTPUT"
                echo "release=$release" >> "$GITHUB_OUTPUT"
                commit=$(grep "$release\$" < remote | cut -f 1)
                echo "commit=$commit" >> "$GITHUB_OUTPUT"
                echo Building release $release at commit $commit
                break
              fi
            done
            if ! grep -x "action=BUILD" "$GITHUB_OUTPUT" > /dev/null; then
              echo "action=SKIP" >> "$GITHUB_OUTPUT"
            fi
          else
            # release specified manually
            release="${{ inputs.release }}"
            echo "action=BUILD" >> "$GITHUB_OUTPUT"
            echo "release=$release" >> "$GITHUB_OUTPUT"
            commit=$(grep "$release\$" < remote | cut -f 1)
            echo "commit=$commit" >> "$GITHUB_OUTPUT"
            echo Forced building release $release at commit $commit
          fi


  binary:
    name: Create the artifact
    needs: check_build
    permissions:
      id-token: write
      attestations: write
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-15-intel
            name: x86_64-apple-darwin
            installable: .#dune
          - os: macos-14
            name: aarch64-apple-darwin
            installable: .#dune
          - os: ubuntu-22.04
            name: x86_64-unknown-linux-musl
            installable: .#dune-static

    # if we have nothing new to build, skip
    if: ${{ needs.check_build.outputs.action == 'BUILD' }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout dune
        uses: actions/checkout@v6
        with:
          repository: ocaml/dune
          ref: ${{ needs.check_build.outputs.release }}
          fetch-depth: 1

      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: dune-binary-distribution

      - uses: cachix/install-nix-action@v31

      - name: Set version
        run: |
          echo "(version ${{ needs.check_build.outputs.release }})" >> dune-project

      - run: nix build ${{ matrix.installable }}

      - name: Generate artifact attestation
        id: certificate
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "result/bin/dune"
          show-summary: false

      - name: Extract artifact and attestation
        run: |
          ARCHIVE_DIR="dune-${{ needs.check_build.outputs.release }}-${{ matrix.name }}"
          ARCHIVE_TAR="${ARCHIVE_DIR}.tar"
          mkdir -p ~/build/$ARCHIVE_DIR
          cp ${{ steps.certificate.outputs.bundle-path }} ~/build
          cp result/bin/dune ~/build/$ARCHIVE_DIR
          cp -r $GITHUB_WORKSPACE/dune-binary-distribution/env ~/build/$ARCHIVE_DIR
          cp -r $GITHUB_WORKSPACE/dune-binary-distribution/completions ~/build/$ARCHIVE_DIR
          cp -r $GITHUB_WORKSPACE/dune-binary-distribution/tool-wrappers ~/build/$ARCHIVE_DIR
          tar --format=posix -cvf ~/build/$ARCHIVE_TAR -C ~/build $ARCHIVE_DIR
          gzip -9 ~/build/$ARCHIVE_TAR
          rm -rf ~/build/$ARCHIVE_DIR

      - uses: actions/upload-artifact@v4
        with:
          path: ~/build
          name: ${{ matrix.name }}

  check-artifacts:
    name: Check the artifact
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-15-intel
            name: x86_64-apple-darwin
          - os: macos-14
            name: aarch64-apple-darwin
          - os: ubuntu-22.04
            name: x86_64-unknown-linux-musl

    runs-on: ${{ matrix.os }}
    needs: [check_build, binary]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/download-artifact@v4

      - name: Get dune artifact
        run: |
          ARCHIVE_DIR="dune-${{ needs.check_build.outputs.release }}-${{ matrix.name }}"
          ARCHIVE_TARGZ="${ARCHIVE_DIR}.tar.gz"
          mv ${{ matrix.name }}/$ARCHIVE_TARGZ .
          tar -xvf $ARCHIVE_TARGZ
          mv ./$ARCHIVE_DIR/dune ./dune

      - name: Check dune is working
        run: |
          export PATH="$PWD:$PATH"
          cd test
          dune --version
          dune pkg lock
          dune build

  deploy-s3:
    runs-on: ubuntu-latest
    needs: [check_build, binary, check-artifacts]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install rclone
        run: |
          sudo -v ; curl https://rclone.org/install.sh | sudo bash

      - name: Install dune
        uses: ocaml-dune/setup-dune@v2

      - uses: actions/download-artifact@v4
        with:
          path: /home/runner/artifacts

      - name: Update config to point to test environment
        if: ${{ github.ref == 'refs/heads/staging' || inputs.test }}
        run: |
          sed -i 's#let bucket_dir = .*#let bucket_dir = "/dune/test"#g' ./bin/config.ml
          sed -i 's#let url = .*#let url = "https://get.dune.build/test"#g' ./bin/config.ml
          cat ./bin/config.ml

      - name: "Install Sandworm deps & build"
        run: dune build

      - name: Move artifacts to scope
        run: mv "/home/runner/artifacts" "."

      - name: Prepare SSH env
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/tarides
          echo "$SSH_PUBLIC_KEY" > ~/.ssh/tarides.pub
          chmod 600 ~/.ssh/tarides
          chmod 600 ~/.ssh/tarides.pub
          ssh-keyscan -H "$DEPLOY_SERVER" >> ~/.ssh/known_hosts
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}

      - name: Export Rclone configuration
        run: echo "${{ secrets.RCLONE_CONF }}" >> rclone.conf

      - name: Export executables and generate html
        shell: bash
        run: ./_build/install/default/bin/sandworm sync --commit "${{ needs.check_build.outputs.commit }}" --tag "${{ needs.check_build.outputs.release }}" --metadata metadata-stable.json

      - name: Commit changes to branch
        if: ${{ !inputs.test }}
        run: |
          git config --global user.name 'Sandworm'
          git config --global user.email 'ocaml-dune@users.noreply.github.com'
          (git add metadata-stable.json && \
          git commit -m "Release build ${{ needs.check_build.outputs.release }}" && \
          git push) || echo "No new data" # Prevent from committing empty stuff

  notify:
    runs-on: ubuntu-latest
    needs: [binary, check-artifacts, deploy-s3]
    if: ${{ github.ref == 'refs/heads/main' && !cancelled() && (needs.binary.result == 'failure' || needs.check-artifacts.result == 'failure' || needs.deploy-s3.result == 'failure' ) }}
    steps:
      - name: Post an error message to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: |
            :red_circle: I'm sorry to bother you, but it seems your build is failing:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
